// src/components/Navbar.vue
<template>
  <div>
    <b-nav pills>
      <b-nav-item href="/">iρΣμm</b-nav-item>
      <b-nav-item href="/formler">Roliga Formler</b-nav-item>
      <b-nav-item href="/testpage">Intressant Teori</b-nav-item>
      <b-nav-item href="/testpage">Apodiktiska Bevis</b-nav-item>
      <b-nav-item href="testpage">Kontakt</b-nav-item>
    </b-nav>
  </div>
</template>

<style lang="css">
  .nav {
    background-color: #7D7C9D;
    font-family: 'Ropa Sans', sans-serif;
    font-size: 1.5rem;
  }

  a, a:hover {
    color: #EAEAEA;
  }

  .nav-item:hover {
    background-color: rgba(0,0,0,0.11)
  }


</style>

// mattesida/src/components/navbar/navbar.jsx
import {createSignal} from "solid-js";
import './style.css'

const [pages, setPages] = createSignal([
    { name: "iρΣμm", path: "index.html"},
    { name: "Roliga Formler", path: "formler.html"},
    { name: "Intressant Teori", path: "teori.html"},
    { name: "Apodiktiska Bevis", path: "bevis.html"},
    { name: "Kontakt", path: "kontakt.html"}
])

export default () =>
    <nav>
        <ul>
            <For each={pages()}>{(page, i)=>
                <li>
                    <a href={page.path}>{page.name}</a>
                </li>
            }</For>
        </ul>
    </nav>
